spring:
  profiles:
    active:
      - dog
      - EN
      - prod

guru:
  username: YmlUsername
  password: YmlDbPass
  jdbcUrl: YmlJdbcUrl

---
spring:
  profiles: prod
guru:
  username: ProdYmlUsername
  password: ProdYmlDbPass
  jdbcUrl: ProdYmlJdbcUrl